-- 코드를 작성해주세요
SELECT A.ID, IF(ISNULL(B.CHILD_COUNT), 0, B.CHILD_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN(
    SELECT PARENT_ID AS ID , COUNT(ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) B
ON A.ID=B.ID
ORDER BY ID 