SELECT i.id AS ID , n.FISH_NAME AS FISH_NAME, i.LENGTH AS LENGTH
FROM FISH_INFO AS i
 JOIN FISH_NAME_INFO AS n
on i.FISH_TYPE=n.FISH_TYPE
WHERE (i.LENGTH, i.FISH_TYPE) IN (
    SELECT MAX(LENGTH), FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID;